name: CI Tests

on:
  - pull_request
  - push

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.18.0"
      - run: go install github.com/google/addlicense@latest
      - run: env bash -c 'addlicense --check -c "Google LLC" -l MIT src/**/* bin/* examples/**/*'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20"
          - "22"
          - "24"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: npm test
      - run: npm outdated
        continue-on-error: true

  check-package-lock:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm install --package-lock-only --ignore-scripts
      - run: "git diff --exit-code -- package-lock.json || (echo 'Error: package-lock.json is changed during npm install! Please make sure to use npm >= 6.9.0 and commit package-lock.json.' && false)"
